artifact_location: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/8. Retencion Empleados/notebooks/../model_tracking/0
creation_time: 1732957228842
experiment_id: '0'
last_update_time: 1732957228842
lifecycle_stage: active
name: Default
