artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/8. Retencion Empleados/notebooks/../model_tracking/363349613606567808/18c518eaac3f43f9929d7f217a2ad3f1/artifacts
end_time: 1732963964606
entry_point_name: ''
experiment_id: '363349613606567808'
lifecycle_stage: active
run_id: 18c518eaac3f43f9929d7f217a2ad3f1
run_name: gifted-wolf-933
run_uuid: 18c518eaac3f43f9929d7f217a2ad3f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1732963954725
status: 4
tags: []
user_id: Miguel
