artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/8. Retencion Empleados/notebooks/../model_tracking/363349613606567808/cbd12a01268e4d6d8b73d3ace195f04d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '363349613606567808'
lifecycle_stage: active
run_id: cbd12a01268e4d6d8b73d3ace195f04d
run_name: nebulous-lynx-844
run_uuid: cbd12a01268e4d6d8b73d3ace195f04d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732964737806
status: 1
tags: []
user_id: Miguel
