artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/8. Retencion Empleados/notebooks/../model_tracking/363349613606567808/cd4a5c8aca0f4438a8c1d8051b5cee6c/artifacts
end_time: 1732963945928
entry_point_name: ''
experiment_id: '363349613606567808'
lifecycle_stage: active
run_id: cd4a5c8aca0f4438a8c1d8051b5cee6c
run_name: stylish-bear-994
run_uuid: cd4a5c8aca0f4438a8c1d8051b5cee6c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732963877468
status: 4
tags: []
user_id: Miguel
